openapi: "3.0.1"
info:
  title: "Combined API"
  version: "1.0"
servers:
  - url: "https://localhost:7044/"
    description: "Employee API Server"
  - url: "https://localhost:7207/"
    description: "Contact API Server"

paths:
  "/employee":
    get:
      tags:
        - "Employee"
      responses:
        "200":
          description: "Success"
          content:
            text/plain:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Employee"
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Employee"
            text/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Employee"
    post:
      tags:
        - "Employee"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Employee"
          text/json:
            schema:
              $ref: "#/components/schemas/Employee"
          application/*+json:
            schema:
              $ref: "#/components/schemas/Employee"
      responses:
        "200":
          description: "Success"
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/Employee"
            application/json:
              schema:
                $ref: "#/components/schemas/Employee"
            text/json:
              schema:
                $ref: "#/components/schemas/Employee"

  "/employee/{id}":
    get:
      tags:
        - "Employee"
      parameters:
        - name: "id"
          in: "path"
          required: true
          style: "simple"
          schema:
            type: "integer"
            format: "int32"
      responses:
        "200":
          description: "Success"
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/Employee"
            application/json:
              schema:
                $ref: "#/components/schemas/Employee"
            text/json:
              schema:
                $ref: "#/components/schemas/Employee"
    put:
      tags:
        - "Employee"
      parameters:
        - name: "id"
          in: "path"
          required: true
          style: "simple"
          schema:
            type: "integer"
            format: "int32"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Employee"
          text/json:
            schema:
              $ref: "#/components/schemas/Employee"
          application/*+json:
            schema:
              $ref: "#/components/schemas/Employee"
      responses:
        "200":
          description: "Success"
    delete:
      tags:
        - "Employee"
      parameters:
        - name: "id"
          in: "path"
          required: true
          style: "simple"
          schema:
            type: "integer"
            format: "int32"
      responses:
        "200":
          description: "Success"

  "/contact":
    get:
      tags:
        - "Contact"
      servers:
        - url: "https://localhost:7207/"
      responses:
        "200":
          description: "Success"
          content:
            text/plain:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Contact"
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Contact"
            text/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Contact"
    post:
      tags:
        - "Contact"
      servers:
        - url: "https://localhost:7207/"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Contact"
          text/json:
            schema:
              $ref: "#/components/schemas/Contact"
          application/*+json:
            schema:
              $ref: "#/components/schemas/Contact"
      responses:
        "200":
          description: "Success"
          content:
            text/plain:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Contact"
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Contact"
            text/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Contact"

  "/contact/{id}":
    get:
      tags:
        - "Contact"
      servers:
        - url: "https://localhost:7207/"
      parameters:
        - name: "id"
          in: "path"
          required: true
          style: "simple"
          schema:
            type: "integer"
            format: "int32"
      responses:
        "200":
          description: "Success"
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/Contact"
            application/json:
              schema:
                $ref: "#/components/schemas/Contact"
            text/json:
              schema:
                $ref: "#/components/schemas/Contact"
    put:
      tags:
        - "Contact"
      servers:
        - url: "https://localhost:7207/"
      parameters:
        - name: "id"
          in: "path"
          required: true
          style: "simple"
          schema:
            type: "integer"
            format: "int32"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Contact"
          text/json:
            schema:
              $ref: "#/components/schemas/Contact"
          application/*+json:
            schema:
              $ref: "#/components/schemas/Contact"
      responses:
        "200":
          description: "Success"
          content:
            text/plain:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Contact"
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Contact"
            text/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Contact"
    delete:
      tags:
        - "Contact"
      servers:
        - url: "https://localhost:7207/"
      parameters:
        - name: "id"
          in: "path"
          required: true
          style: "simple"
          schema:
            type: "integer"
            format: "int32"
      responses:
        "200":
          description: "Success"
          content:
            text/plain:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Contact"
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Contact"
            text/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Contact"

components:
  schemas:
    DateOnly:
      type: "object"
      properties:
        year:
          type: "integer"
          format: "int32"
        month:
          type: "integer"
          format: "int32"
        day:
          type: "integer"
          format: "int32"
        dayOfWeek:
          $ref: "#/components/schemas/DayOfWeek"
        dayOfYear:
          type: "integer"
          format: "int32"
          readOnly: true
        dayNumber:
          type: "integer"
          format: "int32"
          readOnly: true
      additionalProperties: false

    DayOfWeek:
      enum:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
      type: "integer"
      format: "int32"

    Employee:
      type: "object"
      properties:
        employeeId:
          type: "integer"
          format: "int32"
        name:
          type: "string"
          nullable: true
        age:
          type: "integer"
          format: "int32"
        department:
          type: "string"
          nullable: true
        experience:
          type: "integer"
          format: "int32"
        bloodGroup:
          type: "string"
          nullable: true
        fatherName:
          type: "string"
          nullable: true
        isDeleted:
          type: "boolean"
        isActive:
          type: "boolean"
        dateOfCreated:
          type: "string"
          format: "date-time"
        dateOfUpdated:
          type: "string"
          format: "date-time"
        roles:
          type: "string"
          nullable: true
        isSupervisor:
          type: "boolean"
        isManager:
          type: "boolean"
      additionalProperties: false

    Contact:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
        firstName:
          type: "string"
          nullable: true
        lastName:
          type: "string"
          nullable: true
        nickName:
          type: "string"
          nullable: true
        age:
          type: "integer"
          format: "int32"
        dateTimeCreated:
          type: "string"
          format: "date-time"
        isDeleted:
          type: "boolean"
      additionalProperties: false