/*
 * Combined API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
// uncomment below to import models
//using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing EmployeeApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class EmployeeApiTests : IDisposable
    {
        private EmployeeApi instance;

        public EmployeeApiTests()
        {
            instance = new EmployeeApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EmployeeApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' EmployeeApi
            //Assert.IsType<EmployeeApi>(instance);
        }

        /// <summary>
        /// Test EmployeeGet
        /// </summary>
        [Fact]
        public void EmployeeGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.EmployeeGet();
            //Assert.IsType<List<Employee>>(response);
        }

        /// <summary>
        /// Test EmployeeIdDelete
        /// </summary>
        [Fact]
        public void EmployeeIdDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int id = null;
            //instance.EmployeeIdDelete(id);
        }

        /// <summary>
        /// Test EmployeeIdGet
        /// </summary>
        [Fact]
        public void EmployeeIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int id = null;
            //var response = instance.EmployeeIdGet(id);
            //Assert.IsType<Employee>(response);
        }

        /// <summary>
        /// Test EmployeeIdPut
        /// </summary>
        [Fact]
        public void EmployeeIdPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int id = null;
            //Employee? employee = null;
            //instance.EmployeeIdPut(id, employee);
        }

        /// <summary>
        /// Test EmployeePost
        /// </summary>
        [Fact]
        public void EmployeePostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Employee? employee = null;
            //var response = instance.EmployeePost(employee);
            //Assert.IsType<Employee>(response);
        }
    }
}
