/*
 * Combined API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing Contact
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ContactTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Contact
        //private Contact instance;

        public ContactTests()
        {
            // TODO uncomment below to create an instance of Contact
            //instance = new Contact();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Contact
        /// </summary>
        [Fact]
        public void ContactInstanceTest()
        {
            // TODO uncomment below to test "IsType" Contact
            //Assert.IsType<Contact>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'FirstName'
        /// </summary>
        [Fact]
        public void FirstNameTest()
        {
            // TODO unit test for the property 'FirstName'
        }

        /// <summary>
        /// Test the property 'LastName'
        /// </summary>
        [Fact]
        public void LastNameTest()
        {
            // TODO unit test for the property 'LastName'
        }

        /// <summary>
        /// Test the property 'NickName'
        /// </summary>
        [Fact]
        public void NickNameTest()
        {
            // TODO unit test for the property 'NickName'
        }

        /// <summary>
        /// Test the property 'Age'
        /// </summary>
        [Fact]
        public void AgeTest()
        {
            // TODO unit test for the property 'Age'
        }

        /// <summary>
        /// Test the property 'DateTimeCreated'
        /// </summary>
        [Fact]
        public void DateTimeCreatedTest()
        {
            // TODO unit test for the property 'DateTimeCreated'
        }

        /// <summary>
        /// Test the property 'IsDeleted'
        /// </summary>
        [Fact]
        public void IsDeletedTest()
        {
            // TODO unit test for the property 'IsDeleted'
        }
    }
}
