/*
 * Combined API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing DateOnly
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DateOnlyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DateOnly
        //private DateOnly instance;

        public DateOnlyTests()
        {
            // TODO uncomment below to create an instance of DateOnly
            //instance = new DateOnly();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DateOnly
        /// </summary>
        [Fact]
        public void DateOnlyInstanceTest()
        {
            // TODO uncomment below to test "IsType" DateOnly
            //Assert.IsType<DateOnly>(instance);
        }

        /// <summary>
        /// Test the property 'Year'
        /// </summary>
        [Fact]
        public void YearTest()
        {
            // TODO unit test for the property 'Year'
        }

        /// <summary>
        /// Test the property 'Month'
        /// </summary>
        [Fact]
        public void MonthTest()
        {
            // TODO unit test for the property 'Month'
        }

        /// <summary>
        /// Test the property 'Day'
        /// </summary>
        [Fact]
        public void DayTest()
        {
            // TODO unit test for the property 'Day'
        }

        /// <summary>
        /// Test the property 'DayOfWeek'
        /// </summary>
        [Fact]
        public void DayOfWeekTest()
        {
            // TODO unit test for the property 'DayOfWeek'
        }

        /// <summary>
        /// Test the property 'DayOfYear'
        /// </summary>
        [Fact]
        public void DayOfYearTest()
        {
            // TODO unit test for the property 'DayOfYear'
        }

        /// <summary>
        /// Test the property 'DayNumber'
        /// </summary>
        [Fact]
        public void DayNumberTest()
        {
            // TODO unit test for the property 'DayNumber'
        }
    }
}
