/*
 * Combined API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing Employee
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EmployeeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Employee
        //private Employee instance;

        public EmployeeTests()
        {
            // TODO uncomment below to create an instance of Employee
            //instance = new Employee();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Employee
        /// </summary>
        [Fact]
        public void EmployeeInstanceTest()
        {
            // TODO uncomment below to test "IsType" Employee
            //Assert.IsType<Employee>(instance);
        }

        /// <summary>
        /// Test the property 'EmployeeId'
        /// </summary>
        [Fact]
        public void EmployeeIdTest()
        {
            // TODO unit test for the property 'EmployeeId'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Age'
        /// </summary>
        [Fact]
        public void AgeTest()
        {
            // TODO unit test for the property 'Age'
        }

        /// <summary>
        /// Test the property 'Department'
        /// </summary>
        [Fact]
        public void DepartmentTest()
        {
            // TODO unit test for the property 'Department'
        }

        /// <summary>
        /// Test the property 'Experience'
        /// </summary>
        [Fact]
        public void ExperienceTest()
        {
            // TODO unit test for the property 'Experience'
        }

        /// <summary>
        /// Test the property 'BloodGroup'
        /// </summary>
        [Fact]
        public void BloodGroupTest()
        {
            // TODO unit test for the property 'BloodGroup'
        }

        /// <summary>
        /// Test the property 'FatherName'
        /// </summary>
        [Fact]
        public void FatherNameTest()
        {
            // TODO unit test for the property 'FatherName'
        }

        /// <summary>
        /// Test the property 'IsDeleted'
        /// </summary>
        [Fact]
        public void IsDeletedTest()
        {
            // TODO unit test for the property 'IsDeleted'
        }

        /// <summary>
        /// Test the property 'IsActive'
        /// </summary>
        [Fact]
        public void IsActiveTest()
        {
            // TODO unit test for the property 'IsActive'
        }

        /// <summary>
        /// Test the property 'DateOfCreated'
        /// </summary>
        [Fact]
        public void DateOfCreatedTest()
        {
            // TODO unit test for the property 'DateOfCreated'
        }

        /// <summary>
        /// Test the property 'DateOfUpdated'
        /// </summary>
        [Fact]
        public void DateOfUpdatedTest()
        {
            // TODO unit test for the property 'DateOfUpdated'
        }

        /// <summary>
        /// Test the property 'Roles'
        /// </summary>
        [Fact]
        public void RolesTest()
        {
            // TODO unit test for the property 'Roles'
        }

        /// <summary>
        /// Test the property 'IsSupervisor'
        /// </summary>
        [Fact]
        public void IsSupervisorTest()
        {
            // TODO unit test for the property 'IsSupervisor'
        }

        /// <summary>
        /// Test the property 'IsManager'
        /// </summary>
        [Fact]
        public void IsManagerTest()
        {
            // TODO unit test for the property 'IsManager'
        }
    }
}
